version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall: 
    - location: scripts/init.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after.sh
      timeout: 300
      runas: root
